//require('font-awesome/css/font-awesome.css');
//require('../../css/app.scss');
require('bootstrap/dist/css/bootstrap.css');
require('../../css/sb-admin.css');
require('../../css/layout.css');
require('angular-ui-grid/ui-grid.css');
global.jQuery = require('jquery');
require('bootstrap');
require('angular');
require('angular-animate');
require('angular-ui-bootstrap/ui-bootstrap');
require('angular-ui-grid/ui-grid');

//require('bootstrap-rtl/dist/css/bootstrap-rtl.css');
//require('font-awesome/css/font-awesome.css');
//require('../../font-awesome/fonts/fontawesome-webfont.woff');
//require('../../font-awesome/fonts/fontawesome-webfont.ttf');
//require('../../fonts/glyphicons-halflings-regular.eot');
//require('../../fonts/glyphicons-halflings-regular.svg');
//require('../../fonts/glyphicons-halflings-regular.ttf');
//require('../../fonts/glyphicons-halflings-regular.woff');
//require('../../css/sb-admin-rtl.css');
const ngModule = angular.module('HeroicCRM', ['ngAnimate', 'ui.bootstrap', 'ui.grid']);

require('./authentication')(ngModule);
require('./customer')(ngModule);
require('./opportunity')(ngModule);
require('./profile')(ngModule);
require('./report')(ngModule);
require('./risk')(ngModule);
require('./utility')(ngModule);
